title: Mathias Kemeter
description: Digital Hub
baseurl: "https://mkemeter.github.io"
url: https://mkemeter.github.io

theme: cvless

# site settings
taglong: Software Development Manager @ SAP
tagshort: Software Development Manager

# author settings
author:
  name: Mathias Kemeter
  # email: username@domain.com
photo: assets/files/photo.jpg
# address: Foobar Hall 1.23
# phone: +1 234 567 890

# social media links
social:
  # facebook: username
  bluesky:
    user: kemeter
    domain: rocks
  linkedin: mathiaskemeter
  xing: Mathias_Kemeter
  # instagram: username
  github: mkemeter
  stackoverflow: 16739843/mathias-kemeter
  medium: mkemeter
  # x: username

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never